import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>InnoPoisk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header className = {styles.head}>
          <ul className= {styles.hr}>
              <li><a href="/home">Home</a></li>
              <li><a href="/favourites">Favorites</a></li>
              <li><a href="/settings">Settings</a></li>
          </ul>
      </header>

        <main>
            <h1 className={styles.title}>InnoPoisk</h1>
            <h2 className={styles.slogan}>Search, watch, save favs!</h2>
        </main>
    </div>
  )
}

export default Home
